/* josh w
   4850 final exam
   4/20/2021 */

pipeline {
    agent any
    parameters {
        booleanParam(defaultValue: false, description: 'Whether to Run the Code', name: 'RUN')
        string(defaultValue: 'Latest', description: 'Name of the build', name: 'BUILD_NAME')
    }
    stages {
        stage('Build') {
            steps {
                sh 'echo "Starting Build..."'
                sh 'mvn -B -DskipTests clean package'
                sh 'echo "Build Completed."'
            }
        }
        stage('Code Quantity') {
            steps {
                sh 'wc -l src/main/java/com/mycompany/app/App.java'
            }
        }
        stage('Test') {
            steps {
                sh 'mvn test'
            }
            post {
                always {
                    script { 
                        def test_reports_exist = fileExists 'test-reports'
                        if (test_reports_exist) {                        
                            junit 'test-reports/*.xml'
                        }
                        def api_test_reports_exist = fileExists 'api-test-reports'
                        if (api_test_reports_exist) {                        
                            junit 'api-test-reports/*.xml'
                        }
                    }
                }
            }
        }
        stage('Run') {
            when {
                expression {
                    params.RUN == true
                }
            }
            steps {
               sh 'scripts/deliver.sh'
            }
        }
        stage('Build Results') {
            steps {
                sh "echo 'Build ${BUILD_NAME} completed successfully'"
                sh "echo 'I have now compelted ACIT 4850!'"
            }
        }
    }
}
