/* josh w
   4850 final exam
   4/20/2021 */

pipeline {
    agent any
    parameters {
        booleanParam(defaultValue: false, description: 'Whether to Run the Code', name: 'RUN')
        string(defaultValue: 'Latest', description: 'Name of the build', name: 'BUILD_NAME')
    }
    stages {
        stage('Build') {
            steps {
                sh 'echo "Starting Build..."'
                sh 'mvn -B -DskipTests clean package'
                sh 'echo "Build Completed."'
            }
        }

        stage('Test') {
            steps {
                sh 'mvn test'
            }
            post {
                always {
                    junit 'target/surefire-reports/*.xml'
                }
            }
        }

    }
}
